//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryView
    {
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string EmployeeStatus { get; set; }
        public string EmployeeType { get; set; }
        public string ProductType { get; set; }
        public string Product { get; set; }
        public int IdEmployeeType { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
